name: TestFlight status

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  TestFlight:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v4

    -
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: pip

    -
      run: pip install -r scripts/requirements.txt

    -
      id: testflight
      run: python scripts/main.py
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}